# This workflow automatically creates a PR bumping datadog-ci in the CI integration.

name: Bump Datadog CI

on:
  workflow_dispatch:
    inputs:
      datadog_ci_version:
        description: 'Version of datadog-ci to install (`latest` or `major.minor.patch`)'
        type: string
        default: 'latest'

jobs:
  bump-datadog-ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate tokens.
    steps:
      # Do the changes
      - name: Get GitHub token via dd-octo-sts
        id: octo-sts
        uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        with:
          scope: DataDog/synthetics-ci-github-action
          policy: self.bump-datadog-ci.create-pr
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.octo-sts.outputs.token }}
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Create release branch
        run: git checkout -b local-branch
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
      - name: Install dependencies
        run: yarn install
      - name: Bump datadog-ci
        id: bump-datadog-ci
        run: |
          VERSION=${{ github.event.inputs.datadog_ci_version }}
          if [ "$VERSION" = "latest" ]; then
            VERSION=$(npm view @datadog/datadog-ci --json | jq -r '.version')
          fi

          yarn add @datadog/datadog-ci@^$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Create bump commit
        run: git commit -a --message '[dep] Bump datadog-ci to `${{ steps.bump-datadog-ci.outputs.VERSION }}`'
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
      - name: Push the branch
        run: git push -u origin local-branch:bump-datadog-ci/${{ steps.bump-datadog-ci.outputs.VERSION }}
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}

      # Create the pull request
      - name: Create pull request
        id: create-pull-request
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'main',
              head: 'bump-datadog-ci/${{ steps.bump-datadog-ci.outputs.VERSION }}',
              title: '[dep] Bump datadog-ci to `${{ steps.bump-datadog-ci.outputs.VERSION }}`',
              body: 'This PR bumps [datadog-ci](https://github.com/DataDog/datadog-ci) to version [`${{ steps.bump-datadog-ci.outputs.VERSION }}`](https://github.com/DataDog/datadog-ci/releases/tag/v${{ steps.bump-datadog-ci.outputs.VERSION }})'
            })

            core.setOutput('PULL_REQUEST_NUMBER', pullRequest.number)
      - name: Create comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          script: |
            const body = `This PR was automatically created because a new version of datadog-ci was published.

            > [!IMPORTANT]
            > **You are not done!**
            >
            > Once this PR is merged, please run the ["Create Release PR" workflow](../actions/workflows/release-version.yml).
            > This time, it will create a **release PR** for you, which will publish the CI integration once merged.`

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.create-pull-request.outputs.PULL_REQUEST_NUMBER }},
              body,
            })
